//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterMusicRestApiDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicTable
    {
        public int Id { get; set; }
        public string ArtName { get; set; }
        public string SongName { get; set; }
        public string Duration { get; set; }
        public string AlbumName { get; set; }
        public string ArtLastName { get; set; }
        public string SongPath { get; set; }
        public string BackgroundPath { get; set; }
        public string ArtistPath { get; set; }
        public string AlbumPath { get; set; }
    }
}
